select * from customer limit 20


--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' 
and purchase_amount>(select avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount) from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) as percnt
from customer 
group by item_purchased
order by percnt desc
limit 5	

--Q7. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_cust 
from customer
where previous_purchases>5
group by subscription_status


--Q8. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


-- Q9. Which payment methods generate the highest revenue?
SELECT
    payment_method,
    COUNT(*) AS total_orders,
    ROUND(SUM(purchase_amount),2) AS total_revenue,
    ROUND(AVG(purchase_amount),2) AS avg_order_value
FROM customer
GROUP BY payment_method
ORDER BY total_revenue DESC;

-- Q10. Which season contributes the highest sales?
SELECT
    season,
    COUNT(*) AS total_orders,
    ROUND(SUM(purchase_amount),2) AS total_revenue,
    ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;